
   INFO  Running migrations.  

  2014_10_12_100000_create_password_reset_tokens_table .........................................................................  
  ⇂ create table "password_reset_tokens" ("email" varchar(255) not null, "token" varchar(255) not null, "created_at" timestamp(0) without time zone null)  
  ⇂ alter table "password_reset_tokens" add primary key ("email")  
  2016_06_01_000001_create_oauth_auth_codes_table ..............................................................................  
  ⇂ create table "oauth_auth_codes" ("id" varchar(100) not null, "user_id" bigint not null, "client_id" bigint not null, "scopes" text null, "revoked" boolean not null, "expires_at" timestamp(0) without time zone null)  
  ⇂ alter table "oauth_auth_codes" add primary key ("id")  
  ⇂ create index "oauth_auth_codes_user_id_index" on "oauth_auth_codes" ("user_id")  
  2016_06_01_000002_create_oauth_access_tokens_table ...........................................................................  
  ⇂ create table "oauth_access_tokens" ("id" varchar(100) not null, "user_id" bigint null, "client_id" bigint not null, "name" varchar(255) null, "scopes" text null, "revoked" boolean not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null, "expires_at" timestamp(0) without time zone null)  
  ⇂ alter table "oauth_access_tokens" add primary key ("id")  
  ⇂ create index "oauth_access_tokens_user_id_index" on "oauth_access_tokens" ("user_id")  
  2016_06_01_000003_create_oauth_refresh_tokens_table ..........................................................................  
  ⇂ create table "oauth_refresh_tokens" ("id" varchar(100) not null, "access_token_id" varchar(100) not null, "revoked" boolean not null, "expires_at" timestamp(0) without time zone null)  
  ⇂ alter table "oauth_refresh_tokens" add primary key ("id")  
  ⇂ create index "oauth_refresh_tokens_access_token_id_index" on "oauth_refresh_tokens" ("access_token_id")  
  2016_06_01_000004_create_oauth_clients_table .................................................................................  
  ⇂ create table "oauth_clients" ("id" bigserial not null primary key, "user_id" bigint null, "name" varchar(255) not null, "secret" varchar(100) null, "provider" varchar(255) null, "redirect" text not null, "personal_access_client" boolean not null, "password_client" boolean not null, "revoked" boolean not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ create index "oauth_clients_user_id_index" on "oauth_clients" ("user_id")  
  2016_06_01_000005_create_oauth_personal_access_clients_table .................................................................  
  ⇂ create table "oauth_personal_access_clients" ("id" bigserial not null primary key, "client_id" bigint not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2019_08_19_000000_create_failed_jobs_table ...................................................................................  
  ⇂ create table "failed_jobs" ("id" bigserial not null primary key, "uuid" varchar(255) not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" timestamp(0) without time zone not null default CURRENT_TIMESTAMP)  
  ⇂ alter table "failed_jobs" add constraint "failed_jobs_uuid_unique" unique ("uuid")  
  2019_12_14_000001_create_personal_access_tokens_table ........................................................................  
  ⇂ create table "personal_access_tokens" ("id" bigserial not null primary key, "tokenable_type" varchar(255) not null, "tokenable_id" bigint not null, "name" varchar(255) not null, "token" varchar(64) not null, "abilities" text null, "last_used_at" timestamp(0) without time zone null, "expires_at" timestamp(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ create index "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id")  
  ⇂ alter table "personal_access_tokens" add constraint "personal_access_tokens_token_unique" unique ("token")  
  2024_11_23_074141_create_permissions_table ...................................................................................  
  ⇂ create table "permissions" ("id" bigserial not null primary key, "name" varchar(255) not null, "description" text null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155014_create_orders_table ........................................................................................  
  ⇂ create table "orders" ("id" bigserial not null primary key, "name" varchar(255) not null, "quantity" integer not null, "status" varchar(255) not null, "start_date" timestamp(0) without time zone not null, "end_date" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155155_create_models_table ........................................................................................  
  ⇂ create table "models" ("id" bigserial not null primary key, "name" varchar(255) not null, "category_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155321_create_units_table .........................................................................................  
  ⇂ create table "units" ("id" bigserial not null primary key, "name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155425_create_razryads_table ......................................................................................  
  ⇂ create table "razryads" ("id" bigserial not null primary key, "name" varchar(255) not null, "salary" decimal(10, 2) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155524_create_attendances_table ...................................................................................  
  ⇂ create table "attendances" ("id" bigserial not null primary key, "employee_id" integer not null, "date" date not null, "check_in" time(0) without time zone null, "check_out" time(0) without time zone null, "work_time" time(0) without time zone null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155639_create_users_table .........................................................................................  
  ⇂ create table "users" ("id" bigserial not null primary key, "name" varchar(255) not null, "username" varchar(255) not null, "phone" varchar(255) not null, "password" varchar(255) not null, "status" varchar(255) check ("status" in ('active', 'inactive')) not null default 'active', "role_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "users" add constraint "users_username_unique" unique ("username")  
  ⇂ alter table "users" add constraint "users_phone_unique" unique ("phone")  
  2024_11_26_155800_create_roles_table .........................................................................................  
  ⇂ create table "roles" ("id" bigserial not null primary key, "name" varchar(255) not null, "description" text null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "roles" add constraint "roles_name_unique" unique ("name")  
  2024_11_26_155822_create_employees_table .....................................................................................  
  ⇂ create table "employees" ("id" bigserial not null primary key, "name" varchar(255) not null, "phone" varchar(255) not null, "group_id" integer null, "user_id" integer null, "payment_type" varchar(255) check ("payment_type" in ('hourly', 'monthly')) not null default 'monthly', "salary" decimal(10, 2) null, "hiring_date" date null, "status" varchar(255) check ("status" in ('active', 'inactive')) not null default 'active', "address" varchar(255) null, "passport_number" varchar(255) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "employees" add constraint "employees_phone_unique" unique ("phone")  
  2024_11_26_155903_create_companies_table .....................................................................................  
  ⇂ create table "companies" ("id" bigserial not null primary key, "name" varchar(255) not null, "img" varchar(255) null, "description" text null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_155926_create_branches_table ......................................................................................  
  ⇂ create table "branches" ("id" bigserial not null primary key, "name" varchar(255) not null, "address" varchar(255) not null, "img" varchar(255) null, "company_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_161504_create_order_models_table ..................................................................................  
  ⇂ create table "order_models" ("id" bigserial not null primary key, "model_id" integer not null, "order_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_162338_create_groups_table ........................................................................................  
  ⇂ create table "groups" ("id" bigserial not null primary key, "name" varchar(255) not null, "responsible_user_id" integer not null, "department_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_26_165619_departments ................................................................................................  
  ⇂ create table "departments" ("id" bigserial not null primary key, "name" varchar(255) not null, "responsible_user_id" integer not null, "branch_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_11_29_113644_drop_column_tu_users_table .................................................................................  
  ⇂ alter table "users" drop column "phone"  
  ⇂ alter table "users" drop column "name"  
  2024_11_29_113812_alter_column_to_users_table ................................................................................  
  ⇂ alter table "users" drop column "status"  
  2024_11_29_122818_drop_column_to_employees ...................................................................................  
  ⇂ alter table "employees" drop column "status"  
  2024_11_29_122852_add_column_to_employees_table ..............................................................................  
  ⇂ alter table "employees" add column "status" boolean not null default '1'  
  2024_11_29_154540_add_column_to_employees_table ..............................................................................  
  ⇂ alter table "employees" add column "img" varchar(255) null  
  2024_11_30_051213_add_column_to_users_table ..................................................................................  
  ⇂ alter table "users" add column "is_active" boolean not null default '1'  
  2024_11_30_054651_add_column_to_users_table ..................................................................................  
  ⇂ alter table "users" drop column "is_active"  
  2024_11_30_065127_drop_column_employees_table ................................................................................  
  ⇂ alter table "employees" drop column "payment_type"  
  2024_11_30_065227_add_column_to_employees_table ..............................................................................  
  ⇂ alter table "employees" add column "payment_type" varchar(255) not null  
  2024_11_30_104355_drop_column_to_attendance_table ............................................................................  
  ⇂ alter table "attendances" drop column "work_time"  
  2024_12_01_072349_create_lids_table ..........................................................................................  
  ⇂ create table "lids" ("id" bigserial not null primary key, "name" varchar(255) not null, "phone" varchar(255) not null, "address" varchar(255) not null, "status" varchar(255) not null, "comment" text null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_01_110736_add_column_to_employees_table ..............................................................................  
  ⇂ alter table "employees" add column "comment" text null  
  2024_12_02_045609_add_column_to_employees_table ..............................................................................  
  ⇂ alter table "employees" add column "branch_id" integer null  
  2024_12_06_085530_create_categories_table ....................................................................................  
  ⇂ create table "categories" ("id" bigserial not null primary key, "name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_06_090055_create_order_sub_models_table ..............................................................................  
  ⇂ create table "order_sub_models" ("id" bigserial not null primary key, "order_model_id" integer not null, "submodel_id" integer not null, "size_id" integer not null, "quantity" integer not null, "recipe_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_06_090404_create_sub_models_table ....................................................................................  
  ⇂ create table "sub_models" ("id" bigserial not null primary key, "name" varchar(255) not null, "model_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_06_090439_create_sizes_table .........................................................................................  
  ⇂ create table "sizes" ("id" bigserial not null primary key, "name" varchar(255) not null, "submodel_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_06_090518_create_recipes_table .......................................................................................  
  ⇂ create table "recipes" ("id" bigserial not null primary key, "size_id" integer not null, "item_id" integer not null, "color_id" integer not null, "quantity" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_06_090625_create_colors_table ........................................................................................  
  ⇂ create table "colors" ("id" bigserial not null primary key, "name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_06_090646_create_items_table .........................................................................................  
  ⇂ create table "items" ("id" bigserial not null primary key, "name" varchar(255) not null, "price" integer not null, "unit_id" integer not null, "color_id" integer not null, "image" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_07_045932_create_model_colors_table ..................................................................................  
  ⇂ create table "model_colors" ("id" bigserial not null primary key, "name" varchar(255) not null, "size_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_07_050109_drop_column_to_recipes_table ...............................................................................  
  ⇂ alter table "recipes" drop column "size_id"  
  2024_12_07_052721_create_products_table ......................................................................................  
  ⇂ create table "products" ("id" bigserial not null primary key, "name" varchar(200) not null, "description" varchar(200) null, "unit" varchar(255) not null, "price" decimal(16, 2) not null, "quantity" double precision not null, "img" varchar(255) null, "color_id" bigint not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "products" add constraint "products_color_id_foreign" foreign key ("color_id") references "colors" ("id") on delete restrict on update cascade  
  ⇂ comment on column "products"."name" is 'Mahsulot nomi'  
  ⇂ comment on column "products"."description" is 'Tavsif'  
  ⇂ comment on column "products"."unit" is 'O‘lchov birligi'  
  ⇂ comment on column "products"."price" is 'Narx'  
  ⇂ comment on column "products"."quantity" is 'Miqdor'  
  ⇂ comment on column "products"."img" is 'Rasm yo‘li'  
  2024_12_07_085551_drop_column_to_products_table ..............................................................................  
  ⇂ alter table "products" drop column "unit"  
  2024_12_07_085649_add_column_to_products_table ...............................................................................  
  ⇂ alter table "products" add column "unit_id" bigint not null  
  ⇂ alter table "products" add constraint "products_unit_id_foreign" foreign key ("unit_id") references "units" ("id") on delete restrict  
  2024_12_07_095040_create_warehouses_table ....................................................................................  
  ⇂ create table "warehouses" ("id" bigserial not null primary key, "name" varchar(200) not null, "location" varchar(300) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ comment on column "warehouses"."name" is 'Ombor nomi'  
  ⇂ comment on column "warehouses"."location" is 'Manzil'  
  2024_12_07_104100_create_warehouse_user_table ................................................................................  
  ⇂ create table "warehouse_user" ("id" bigserial not null primary key, "warehouse_id" bigint not null, "user_id" bigint not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "warehouse_user" add constraint "warehouse_user_warehouse_id_foreign" foreign key ("warehouse_id") references "warehouses" ("id") on delete cascade  
  ⇂ alter table "warehouse_user" add constraint "warehouse_user_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade  
  2024_12_07_110759_drop_column_to_model_colors_table ..........................................................................  
  ⇂ alter table "model_colors" drop column "size_id"  
  2024_12_07_110824_add_column_to_model_colors_table ...........................................................................  
  ⇂ alter table "model_colors" add column "submodel_id" integer not null  
  2024_12_07_122829_drop_column_to_model_colors_table ..........................................................................  
  ⇂ alter table "model_colors" drop column "name"  
  2024_12_07_122857_add_column_to_model_colors_table ...........................................................................  
  ⇂ alter table "model_colors" add column "color_id" varchar(255) not null  
  2024_12_07_125728_rename_column_in_recipes_table .............................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2024_12_07_125728_rename_column_in_recipes_table.php:7$1b0] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2024_12_07_131836_add_column_in_recipes_table ................................................................................  
  ⇂ alter table "recipes" add column "size_id" integer null  
  2024_12_07_141529_create_product_categories_table ............................................................................  
  ⇂ create table "product_categories" ("id" bigserial not null primary key, "name" varchar(200) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ comment on column "product_categories"."name" is 'Kategoriya nomi'  
  2024_12_07_141601_create_providers_table .....................................................................................  
  ⇂ create table "providers" ("id" bigserial not null primary key, "name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_07_141626_create_out_come_types_table ................................................................................  
  ⇂ create table "outcome_types" ("id" bigserial not null primary key, "name" varchar(255) not null, "user_id" bigint not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "outcome_types" add constraint "outcome_types_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade  
  2024_12_07_141657_create_incomes_table .......................................................................................  
  ⇂ create table "incomes" ("id" bigserial not null primary key, "product_id" bigint not null, "quantity" double precision not null, "warehouse_id" bigint not null, "barcode" uuid not null, "type_id" bigint not null, "provider_id" bigint not null, "order_id" bigint null, "model_id" bigint null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "incomes" add constraint "incomes_product_id_foreign" foreign key ("product_id") references "items" ("id") on delete restrict  
  ⇂ alter table "incomes" add constraint "incomes_warehouse_id_foreign" foreign key ("warehouse_id") references "warehouses" ("id") on delete cascade  
  ⇂ alter table "incomes" add constraint "incomes_type_id_foreign" foreign key ("type_id") references "product_categories" ("id") on delete restrict  
  ⇂ alter table "incomes" add constraint "incomes_provider_id_foreign" foreign key ("provider_id") references "providers" ("id") on delete restrict  
  ⇂ alter table "incomes" add constraint "incomes_order_id_foreign" foreign key ("order_id") references "orders" ("id") on delete set null  
  ⇂ alter table "incomes" add constraint "incomes_model_id_foreign" foreign key ("model_id") references "order_models" ("id") on delete set null  
  ⇂ alter table "incomes" add constraint "incomes_barcode_unique" unique ("barcode")  
  2024_12_07_141743_create_ware_house_stocks_table .............................................................................  
  ⇂ create table "warehouse_stocks" ("id" bigserial not null primary key, "warehouse_id" bigint not null, "product_id" bigint not null, "current_quantity" decimal(16, 2) not null default '0', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "warehouse_stocks" add constraint "warehouse_stocks_warehouse_id_foreign" foreign key ("warehouse_id") references "warehouses" ("id") on delete restrict  
  ⇂ alter table "warehouse_stocks" add constraint "warehouse_stocks_product_id_foreign" foreign key ("product_id") references "items" ("id") on delete restrict  
  ⇂ alter table "warehouse_stocks" add constraint "warehouse_stocks_warehouse_id_product_id_unique" unique ("warehouse_id", "product_id")  
  2024_12_07_141808_create_out_comes_table .....................................................................................  
  ⇂ create table "outcomes" ("id" bigserial not null primary key, "product_id" bigint not null, "quantity" double precision not null, "warehouse_id" bigint not null, "barcode" uuid not null, "provider_id" bigint not null, "outcome_type_id" bigint not null, "order_id" bigint null, "model_id" bigint null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "outcomes" add constraint "outcomes_product_id_foreign" foreign key ("product_id") references "items" ("id") on delete cascade  
  ⇂ alter table "outcomes" add constraint "outcomes_warehouse_id_foreign" foreign key ("warehouse_id") references "warehouses" ("id") on delete cascade  
  ⇂ alter table "outcomes" add constraint "outcomes_provider_id_foreign" foreign key ("provider_id") references "providers" ("id") on delete restrict  
  ⇂ alter table "outcomes" add constraint "outcomes_outcome_type_id_foreign" foreign key ("outcome_type_id") references "outcome_types" ("id") on delete restrict  
  ⇂ alter table "outcomes" add constraint "outcomes_order_id_foreign" foreign key ("order_id") references "orders" ("id") on delete set null  
  ⇂ alter table "outcomes" add constraint "outcomes_model_id_foreign" foreign key ("model_id") references "order_models" ("id") on delete set null  
  ⇂ alter table "outcomes" add constraint "outcomes_barcode_unique" unique ("barcode")  
  2024_12_07_153448_create_item_types_table ....................................................................................  
  ⇂ create table "item_types" ("id" bigserial not null primary key, "name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_07_153553_add_column_to_items_table ..................................................................................  
  ⇂ alter table "items" add column "type_id" integer not null default '1'  
  2024_12_08_061644_add_column_to_items_table ..................................................................................  
  ⇂ alter table "items" add column "code" varchar(255) null  
  ⇂ alter table "items" add constraint "items_code_unique" unique ("code")  
  2024_12_08_064217_rename_column_to_recipes_table .............................................................................  

  2024_12_11_134839_modify_column_to_order_sub_models_table ....................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2024_12_11_134839_modify_column_to_order_sub_models_table.php:7$1d4] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2024_12_12_131234_create_details_table .......................................................................................  
  ⇂ create table "details" ("id" bigserial not null primary key, "submodel_id" integer not null, "detail_category_id" integer not null, "name" varchar(255) not null, "razryad_id" integer not null, "machine" varchar(255) not null, "second" integer not null, "summa" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_12_131751_create_detail_categories_table .............................................................................  
  ⇂ create table "detail_categories" ("id" bigserial not null primary key, "name" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_14_063459_create_jobs_table ..........................................................................................  
  ⇂ create table "jobs" ("id" bigserial not null primary key, "queue" varchar(255) not null, "payload" text not null, "attempts" smallint not null, "reserved_at" integer null, "available_at" integer not null, "created_at" integer not null)  
  ⇂ create index "jobs_queue_index" on "jobs" ("queue")  
  2024_12_15_100455_create_applications_table ..................................................................................  
  ⇂ create table "applications" ("id" bigserial not null primary key, "name" varchar(255) not null, "submodel_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_15_100554_create_lining_preparations_table ...........................................................................  
  ⇂ create table "lining_preparations" ("id" bigserial not null primary key, "name" varchar(255) not null, "application_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_15_100748_create_lining_applications_table ...........................................................................  
  ⇂ create table "lining_applications" ("id" bigserial not null primary key, "name" varchar(255) not null, "lining_preparation_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_18_181836_add_column_to_items_table ..................................................................................  
  ⇂ alter table "items" add column "qr_code" varchar(255) null  
  2024_12_21_142216_create_order_recipes_table .................................................................................  
  ⇂ create table "order_recipes" ("id" bigserial not null primary key, "order_id" integer not null, "item_id" integer not null, "model_color_id" integer not null, "quantity" double precision not null, "size_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_21_143845_add_column_to_orders_table .................................................................................  
  ⇂ alter table "orders" add column "rasxod" integer null  
  2024_12_21_144311_add_column_to_order_models_table ...........................................................................  
  ⇂ alter table "order_models" add column "rasxod" integer null  
  2024_12_21_153108_modify_column_to_orders_table ..............................................................................  

  2024_12_21_155145_modify_column_to_order_models_table ........................................................................  

  2024_12_21_155307_add_column_to_models_table .................................................................................  
  ⇂ alter table "models" add column "rasxod" double precision null  
  2024_12_22_145730_add_column_to_lining_applications_table ....................................................................  
  ⇂ alter table "lining_applications" add column "user_id" integer not null  
  2024_12_24_113526_create_model_images_table ..................................................................................  
  ⇂ create table "model_images" ("id" bigserial not null primary key, "model_id" integer not null, "image" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_26_192507_create_type_writers_table ..................................................................................  
  ⇂ create table "type_writers" ("id" bigserial not null primary key, "name" varchar(255) not null, "comment" varchar(255) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_26_192615_create_specification_categories_table ......................................................................  
  ⇂ create table "specification_categories" ("id" bigserial not null primary key, "name" varchar(255) not null, "submodel_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_26_192713_create_part_specifications_table ...........................................................................  
  ⇂ create table "part_specifications" ("id" bigserial not null primary key, "specification_category_id" integer not null, "code" varchar(255) not null, "name" varchar(255) not null, "quantity" integer not null default '1', "comment" text not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_26_193031_create_tarification_categories_table .......................................................................  
  ⇂ create table "tarification_categories" ("id" bigserial not null primary key, "name" varchar(255) not null, "submodel_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2024_12_26_193135_create_tarifications_table .................................................................................  
  ⇂ create table "tarifications" ("id" bigserial not null primary key, "tarification_category_id" integer not null, "user_id" integer not null, "name" varchar(255) not null, "razryad_id" integer not null, "typewriter_id" integer not null, "second" double precision not null, "summa" double precision not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_01_02_194352_add_column_to_tarification_table ...........................................................................  
  ⇂ alter table "tarifications" add column "code" varchar(255) null  
  2025_01_03_092318_add_column_to_orders_table .................................................................................  
  ⇂ alter table "orders" add column "branch_id" integer null  
  2025_01_04_175213_create_order_groups_table ..................................................................................  
  ⇂ create table "order_groups" ("id" bigserial not null primary key, "order_id" bigint not null, "submodel_id" bigint not null, "group_id" bigint not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "order_groups" add constraint "order_groups_order_id_foreign" foreign key ("order_id") references "orders" ("id") on delete cascade  
  ⇂ alter table "order_groups" add constraint "order_groups_submodel_id_foreign" foreign key ("submodel_id") references "sub_models" ("id") on delete cascade  
  ⇂ alter table "order_groups" add constraint "order_groups_group_id_foreign" foreign key ("group_id") references "groups" ("id") on delete cascade  
  ⇂ alter table "order_groups" add constraint "order_submodel_group_unique" unique ("order_id", "submodel_id", "group_id")  
  2025_01_08_115038_add_column_to_employees_table ..............................................................................  
  ⇂ alter table "employees" add column "department_id" integer null  
  2025_01_09_190112_create_submodel_spends_table ...............................................................................  
  ⇂ create table "submodel_spends" ("id" bigserial not null primary key, "submodel_id" integer not null, "seconds" double precision not null, "summa" double precision not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_01_13_165449_create_constructor_orders_table ............................................................................  
  ⇂ create table "constructor_orders" ("id" bigserial not null primary key, "order_model_id" integer not null, "submodel_id" integer not null, "size_id" integer not null, "quantity" integer not null, "status" varchar(255) not null default 'printing', "comment" text null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_01_14_092357_create_order_printing_times_table ..........................................................................  
  ⇂ create table "order_printing_times" ("id" bigserial not null primary key, "order_model_id" integer not null, "planned_time" timestamp(0) without time zone not null, "actual_time" timestamp(0) without time zone null, "status" varchar(255) not null default 'printing', "comment" text null, "user_id" integer null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_01_15_111608_add_column_to_model_colors_table ...........................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2025_01_15_111608_add_column_to_model_colors_table.php:7$1f0] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2025_01_15_140138_rename_column_to_sizes_table ...............................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2025_01_15_140138_rename_column_to_sizes_table.php:7$1f1] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2025_01_15_141859_add_column_to_orders_table .................................................................................  
  ⇂ alter table "orders" add column "contragent_id" integer null, add column "final_product_name" varchar(255) null, add column "comment" text null  
  2025_01_15_142543_create_order_instructions_table ............................................................................  
  ⇂ create table "order_instructions" ("id" bigserial not null primary key, "order_id" bigint not null, "title" varchar(255) not null, "description" text not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "order_instructions" add constraint "order_instructions_order_id_foreign" foreign key ("order_id") references "orders" ("id") on delete cascade  
  2025_01_15_143839_rename_column_to_model_colors_table ........................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2025_01_15_143839_rename_column_to_model_colors_table.php:7$1f4] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2025_01_15_150100_rename_column_to_order_sub_models_table ....................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2025_01_15_150100_rename_column_to_order_sub_models_table.php:7$1f5] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2025_01_17_100653_add_column_to_order_recipes_table ..........................................................................  
  ⇂ alter table "order_recipes" add column "submodel_id" integer null  
  ⇂ alter table "order_recipes" drop column "model_color_id"  
  ⇂ alter table "order_recipes" drop column "size_id"  
  2025_01_18_102809_add_column_to_order_models_table ...........................................................................  
  ⇂ alter table "order_models" add column "material_id" integer null  
  2025_01_18_103053_add_column_to_order_sub_models_table .......................................................................  
  ⇂ alter table "order_sub_models" drop column "size_id"  
  ⇂ alter table "order_sub_models" drop column "quantity"  
  ⇂ alter table "order_sub_models" drop column "materials_id"  
  2025_01_18_103225_create_order_sizes_table ...................................................................................  
  ⇂ create table "order_sizes" ("id" bigserial not null primary key, "size_id" integer not null, "quantity" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_01_18_103443_add_column_to_order_sizes_table ............................................................................  
  ⇂ alter table "order_sizes" add column "order_model_id" integer not null  
  2025_01_18_130119_drop_column_to_orders_table ................................................................................  
  ⇂ alter table "orders" drop column "final_product_name"  
  2025_01_21_110731_rename_column_to_order_printing_times_table ................................................................  

   ERROR  [Illuminate\Database\Migrations\Migration@anonymous database/migrations/2025_01_21_110731_rename_column_to_order_printing_times_table.php:7$1fc] failed to dump queries. This may be due to changing database columns using Doctrine, which is not supported while pretending to run migrations.  

  2025_01_24_165418_create_order_cuts_table ....................................................................................  
  ⇂ create table "order_cuts" ("id" bigserial not null primary key, "order_id" bigint not null, "specification_category_id" bigint not null, "user_id" bigint not null, "cut_at" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  ⇂ alter table "order_cuts" add constraint "order_cuts_order_id_foreign" foreign key ("order_id") references "orders" ("id") on delete cascade  
  ⇂ alter table "order_cuts" add constraint "order_cuts_specification_category_id_foreign" foreign key ("specification_category_id") references "specification_categories" ("id") on delete cascade  
  ⇂ alter table "order_cuts" add constraint "order_cuts_user_id_foreign" foreign key ("user_id") references "users" ("id") on delete cascade  
  2025_01_24_172050_add_column_to_order_cuts_table .............................................................................  
  ⇂ alter table "order_cuts" add column "quantity" integer not null default '0'  
  2025_02_10_161515_create_times_table .........................................................................................  
  ⇂ create table "times" ("id" bigserial not null primary key, "time" time(0) without time zone not null default '00:00:00', "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_02_10_161719_create_sewing_outputs_table ................................................................................  
  ⇂ create table "sewing_outputs" ("id" bigserial not null primary key, "order_submodel_id" integer not null, "quantity" integer not null, "time_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_02_11_172401_create_motivations_table ...................................................................................  
  ⇂ create table "motivations" ("id" bigserial not null primary key, "title" text not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null)  
  2025_02_19_131314_add_column_to_orders_table .................................................................................  
  ⇂ alter table "orders" add column "price" integer not null default '0'  

