name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Fayllarni ro'yxatini olish
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the project directory
        run: ls -la ./VizzanoERP

      # Arxivlash jarayoni
      - name: Create tar archive
        run: |
          tar -cvf /tmp/project_archive.tar ./VizzanoERP/*

      # FTP serverga ulanish va fayllarni uzatish
      - name: Upload to FTP server
        uses: sebastianpopp/ftp-deploy-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}        # FTP server manzili
          username: ${{ secrets.FTP_USERNAME }}  # FTP foydalanuvchi nomi
          password: ${{ secrets.FTP_PASSWORD }}  # FTP parol
          port: 22                              # Port (odatda 22)
          source: /tmp/project_archive.tar      # Arxivlangan fayl manzili
          target: "/home/ftpuser/destination_folder"  # FTP serverdagi target manzil
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
          strip_components: 0
          overwrite: false
          proxy_port: 22
          proxy_timeout: 30s
          proxy_use_insecure_cipher: false
