name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # List files in the project directory
      - name: List files in the project directory
        run: ls -la ./VizzanoERP

      # Create a tar archive of the files
      - name: Create tar archive
        run: |
          tar -cvf /tmp/project_archive.tar ./VizzanoERP/*

      # Upload to FTP server using appleboy/ftp-action
      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}        # FTP server host
          username: ${{ secrets.FTP_USERNAME }}  # FTP username
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password
          port: 22                              # FTP port (usually 22 for SFTP)
          source: /tmp/project_archive.tar      # Path to the tar archive
          target: "/home/ftpuser/destination_folder"  # FTP target directory
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
          strip_components: 0
          overwrite: false
          server: ''
