name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # List files in the project directory to ensure VizzanoERP exists
      - name: List files in the project directory
        run: ls -la

      # Create a tar archive of the files
      - name: Create tar archive
        run: |
          # Ensure the correct directory is targeted
          if [ -d "./VizzanoERP" ]; then
            tar -cvf /tmp/project_archive.tar ./VizzanoERP/*
          else
            echo "Directory ./VizzanoERP not found."
            exit 1
          fi

      # Upload to FTP server using appleboy/ftp-action
      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: /tmp/project_archive.tar
          target: "/home/ftpuser/destination_folder"
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: true
          strip_components: 0
          overwrite: false
          server: ''
