name: Deploy to FTP Server

on:
  push:
    branches:
      - main  # yoki sizning asosiy branch nomingiz

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install FTP Client
        run: sudo apt-get install -y ftp

      - name: Deploy Laravel project to FTP server
        run: |
          ftp -inv ${{ secrets.FTP_SERVER }} <<EOF
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          cd /home/jamkhan/VizzanoERP
          mput -r *
          bye
          EOF
