on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 📦 Install Composer dependencies
        run: |
          composer install --no-dev --no-scripts --no-progress --prefer-dist
      - name: 🧹 Clear Laravel caches
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          exclude: |
            vendor/*
            node_modules/*
            .env
            storage/logs/*
            storage/framework/*
            *.log


      - name: ✅ Deployment Completed
        run: echo "Laravel project successfully deployed to the server!"