on: push
name: 🚀 Deploy Laravel Project via SFTP
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Kodni yuklab olish
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # 2. Composer install ni ishga tushirish
      - name: 📦 Install Composer dependencies
        run: |
          composer install --no-dev --no-scripts --no-progress --prefer-dist

      # 3. Laravelni serverga SFTP orqali yuklash
      - name: 📂 Upload files via SFTP
        uses: appleboy/scp-action@v0.2.3
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22 # SFTP porti (odatda 22 bo‘ladi)
          source: "./" # Yuklanadigan fayllar
          target: "/jamkhan/" # Serverda yuklanadigan papka

      # 4. Tugallanganligini tasdiqlash
      - name: ✅ Deployment Completed
        run: echo "Laravel project successfully deployed via SFTP!"
